
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
mqtt:
 switch:
  - name: Onboard
    command_topic: "device/mate-scale/gpio/led/set"
    state_topic: "device/mate-scale/gpio/led/get"
    payload_on: "1"
    payload_off: "0"
 sensor:
  - name: Charging
    state_topic: "device/mate-scale/gpio/charging/get"
  - name: Temperature
    state_topic: "device/mate-scale/ds18b20/temp/get"
  - name: Battery
    state_topic: "device/mate-scale/adc/battery/get"
  - name: Weight
    state_topic: "device/mate-scale/hx711/weight/get"
  - name: Debug
    state_topic: "device/mate-scale/configured"
    json_attributes_topic: "device/mate-scale/debug"
    
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
