#define INVALID_NAME "N/A"
#define MAX_NAME_LENGTH 50
#define MAX_MODE_LENGTH 50
#define MAX_JSON_DOCUMENT_LENGTH 2048
#define MAX_GPIO_PINS 5
#define MAX_TEMP_SENSORS 5
#define MAX_ADC_PINS 5
#define MAX_SCALES 5